//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        public CAR()
        {
            this.FILL_UP = new HashSet<FILL_UP>();
        }
    
        public string USERNAME { get; set; }
        public string CAR_MAKE { get; set; }
        public string CAR_MODEL { get; set; }
        public Nullable<int> CAR_YEAR { get; set; }
        public int CAR_ID { get; set; }
    
        public virtual MILEAGE_USER MILEAGE_USER { get; set; }
        public virtual ICollection<FILL_UP> FILL_UP { get; set; }
    }
}
