//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class MILEAGE_USER
    {
        public MILEAGE_USER()
        {
            this.CARs = new HashSet<CAR>();
        }
    
        public string USERNAME { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public Nullable<int> OUTPUT_PREF { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<CAR> CARs { get; set; }
    }
}
